app/design/frontend/base/default/layout/turpentine_esi.xml

By default the the search input box is inside the header. 
It needs to contain the current search string after searching, on the search results page.
Before this fix, the header ESI block was cached, so this did not work. The search string was wrong or not showing.

Fix for search input field on search results page

---

app/code/community/Nexcessnet/Turpentine/Block/Core/Messages.php

As requested in https://github.com/nexcess/magento-turpentine/pull/814#issuecomment-114934759 reopening at devel instead of master

Fix messages returning a empty <ul />

---

app/code/community/Nexcessnet/Turpentine/Model/Observer/Esi.php

As requested in https://github.com/nexcess/magento-turpentine/pull/814#issuecomment-114934759 reopening at devel instead of master

Tweak logging for empty getNameInLayout

---

app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl

This is urgent fix for my previous commit. Hit/miss ratio is 0% when using reg.url, because it does not contain hostname i wanted to match against.

[#832] bugfix, reg.url does not contain hostname (leads to permanent request pass, 0 hits)

---

app/code/community/Nexcessnet/Turpentine/Model/Dummy/Request.php

Updated turpentine dummy request to fix unescaped '|' characters in URI

escape | character

---

modman

#499 removed app/code/local/Mage/Core/Model/Session.php in place of a rewrite, but didn't remove the reference to this file from modman. This is currently breaking composer installs in some cases.
Hopefully correct branches this time :)

Removing ref to nonexistent file from modman

---

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php
app/code/community/Nexcessnet/Turpentine/etc/system.xml
app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl

I have been using this code for quite some time to fix an issue with the initial cookie domain setting in VCL.
Basically if you have 2 or more stores e.g.
www.yourstore.co.uk
support.yourstore.co.uk
spares.yourstore.co.uk
With the default configuration for turpentine you will be given a cookie domain regardless of Magento's setting. So you will be given www.yourstore.co.uk domain, support.yourdomain etc.
However if you want to share cookies between those stores to take your basket with you, you need to set it something like: .yourdomain.co.uk which is not possible at the moment without this PR
This adds 2 additional options to the Turpentine settings:
Normalize Cookie Regex: - an example:  ^(www\.|spares\.|support\.)?yoursite\.co\.uk$
Normalized Cookie Target: .yoursite.co.uk
If the vhost …

Allow to override initial cookie domain for multi-store setups

---

app/code/community/Nexcessnet/Turpentine/Helper/Data.php
app/code/community/Nexcessnet/Turpentine/Model/Observer/Esi.php
app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php
app/code/community/Nexcessnet/Turpentine/etc/config.xml
app/code/community/Nexcessnet/Turpentine/etc/system.xml
app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl

Added fix for formKey from https://github.com/deivisonarthur/Inovarti_FixAddToCartMage18/ by Deivison Arthur.

refs Fix from Deivison Arthur for formKey issues and switch between fixes

---

app/design/frontend/base/default/layout/turpentine_esi.xml

I was doing some varnish troubleshooting for a client, and we ran into a situation, using Magento 1.9.0.1, where the cart checkout progress blocks were not bypassing the varnish cache.  We solved this by adding checkout to the turpentine blacklist -- but after investigating a bit I discovered the the approach turpentine takes to exclude checkout progress needs some tweaking.  This pull request is lightly tested -- so consider this more a bug report than anything else.
Also, seems related to @craigcarnell's problems in this ticket 
https://github.com/nexcess/magento-turpentine/issues/455
The basic problem is the `progressAction` method **doesn't** do a full layout load (`loadLayout`)
#File: app/code/local/Mage/Checkout/controllers/OnepageController.php
public function progressAction()
{
// …

Explicit cache bypass for progress sections.

---

app/code/community/Nexcessnet/Turpentine/Block/Product/Compared.php
app/code/community/Nexcessnet/Turpentine/Block/Product/Viewed.php
app/code/community/Nexcessnet/Turpentine/etc/config.xml
app/design/frontend/base/default/layout/turpentine_esi.xml

This should fix the issues with the 'viewed products' and 'recently compared products' https://github.com/nexcess/magento-turpentine/issues/803 and https://github.com/nexcess/magento-turpentine/issues/801
The core problem is that the magento core blocks return nothing if there are no items appropriate for the block. That makes some sense, but it prevents the Turpentine *toHtml()* function from inserting the ESI call into the page for these blocks in that situation.

Fix for viewed/compared blocks #801, #803

---

app/code/community/Nexcessnet/Turpentine/Helper/Esi.php
app/code/community/Nexcessnet/Turpentine/Model/Observer/Esi.php

The config setting [web/unsecure/base_url] can be https://... but ESI can never be HTTPS.
Varnish 3 will treat HTTPS URLs as relative, leading to a 404 in Magento, leading to recursive ESI includes.

Fix for HTTPS ESI URLs

---

app/code/community/Nexcessnet/Turpentine/Model/Config/Select/LoadBalancing.php
app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php
app/code/community/Nexcessnet/Turpentine/etc/config.xml
app/code/community/Nexcessnet/Turpentine/etc/system.xml
app/code/community/Nexcessnet/Turpentine/misc/version-2.vcl
app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl

I had to do a small fix in the VCL because POST requests to Admin need to go trough the Admin backend, or director in case of load balancing.
I have tested the code on a setup with multiple web nodes.

Implemented load balancing support

---

app/design/frontend/base/default/template/turpentine/ajax.phtml

Made the ESI Ajax start 10 ms delay after page load.
The is to make sure the Ajax call is executed async so it does not delay DOMContentLoaded. A shorter time before DOMContentLoaded is better for Google.
I also fixed the jQuery fallback, which did not work because the returned Ajax data was not placed in the div.

Improved ESI Ajax: load async + fixed jQuery fallback.

---

app/code/community/Nexcessnet/Turpentine/Block/Core/Messages.php

When there were no messages, but there was HTML for the ESI container, it was thrown away by code from PR #825. When that happened, there was no ESI container on that page, so messages would never work on that cached page.
This fix is quite urgent since ESI flash messages are broken in the current master branch.

Pull request #825 broke the ESI messages. This commit fixes it.

---

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php

Related to: https://github.com/nexcess/magento-turpentine/issues/918
The versioned banner of Varnish is introduced in Varnish version 3.0.4. In version 3.0 to 3.0.3, the banned has the same behaviour as version 2.1.
Turpentine version 0.6.4 to 0.6.5 has changed the autodetection of the Varnish version. This causes problems in autodetecting the version of varnish 3.0 to 3.0.3. These version will be recognized as version 2.1. The VCL of 2.1 is not compatible with 3.0, which will cause a crash of varnish on reboot or restart.
This Pull-request reverts a small code of 0.6.4 determineVersion https://github.com/nexcess/magento-turpentine/blob/release-0.6.4/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php#L490.
Varnish 3.0.2 is provided by Debian Wheezy or Ubuntu 12.04 by …

DetermineVersion 3.0 to 3.0.3 bugfix

---

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php
app/code/community/Nexcessnet/Turpentine/etc/config.xml
app/code/community/Nexcessnet/Turpentine/etc/system.xml
app/code/community/Nexcessnet/Turpentine/misc/version-2.vcl
app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl
app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl

Hi,
I've fixed my own Issue #935 ;) . It is an optional feature so it will not change the behaviour after an update. Configuration field is here: ``System > Configuration > Turpentine > Caching Options > Parameter-based Caching > Transfer unmodified URL to Backend Server``. 
* The backend server gets the unmodified url (``req.url``)
* Modified url (stripped google parameters...) is saved in ``req.http.X-Varnish-Cache-Url``
*  ``req.http.X-Varnish-Cache-Url`` will be used for cache lookups in ``vcl_hash``
=> The cache hit rate should not be impacted by the changes and the backend server gets accesss to the unmodified url for uncachable requests like rewrites.

Send unmodified url to the backend server

---

app/code/community/Nexcessnet/Turpentine/Model/Observer/Esi.php

Allows layout update data to be cached based on design themes. You can then have device specific widgets based off of the theme match expressions in ESI calls.

Include theme specific handles to ESI data

---

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php
app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl
app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl

When vcl_fix was introduced, return pipe was used. This should only be when generate_session was never called.. I think..

only return pipe when vcl_fix is enabled

---

app/code/community/Nexcessnet/Turpentine/Model/Observer/Esi.php
app/code/community/Nexcessnet/Turpentine/etc/config.xml

Adds the form key to the request when viewing the wishlist page. This prevents '403' issues when adding a wishlist product to the basket (see #497)
If there's a better way of doing this then please let me know as it appears the add to basket issue has been solved in the VCL.

Add the form key to wishlist submit to prevent 403 errors.

---

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php
app/code/community/Nexcessnet/Turpentine/etc/config.xml
app/code/community/Nexcessnet/Turpentine/etc/system.xml
app/code/community/Nexcessnet/Turpentine/misc/version-2.vcl
app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl
app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl

When enabled: Always serve the same version of a static file. Ignore domain, cookies and browser version. Saves memory and lowers cache misses.
Thanks to @toonvd for the idea of this improvement.
Fixed some use of bare booleans in Varnish 2.1 config

"Use Simple Hash" option for static files

---

app/code/community/Nexcessnet/Turpentine/Helper/Data.php

The function `Mage::helper('turpentine/data')->getModelName($product);` did not work in case an extension used in config.xml:
```xml
<models>
<mygroupname>
<class>MyPackage_MyExtension_Model</class>
<mygroupname>
<catalog>
<rewrite>
<product>MyPackage_MyExtension_Model_Product</product>
</rewrite>
</catalog>
</models>
```
Because then the class guessed by `getModelName($product)` was `myextension/product` while it should be `mygroupname/product`.
I made the function check if the guessed value is a valid model name. 
If not valid: the right value is quite hard to look up, so I decided to return the full class name, `MyPackage_MyExtension_Model_Product` in this example.

Improved helper function getModelName()

---

app/code/community/Nexcessnet/Turpentine/Model/Observer/Varnish.php
app/code/community/Nexcessnet/Turpentine/etc/config.xml

Turpentine sets the fake cookie 'frontend=crawler-session' when a crawler is detected.
This causes lock problems with Cm_RedisSession, because all crawler hits are requesting the same session lock.
Cm_RedisSession provides the define CM_REDISSESSION_LOCKING_ENABLED to overrule if locking should be enabled.
I added an 'controller_front_init_before' event listener to set this define if the fake session cookie exists.

Fix for crawler lock problem with CM_RedisSession

---

app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl

This seems to fix https://github.com/nexcess/magento-turpentine/issues/1075
`req.http.Host ~ "{{normalize_cookie_regex}}"` was evaluating to true if no cookie normalize regular expression is set in the back-end, triggering a cookie being set w/no domain. 
The fix requires the normalize regular expression to have at least two characters.

Fix regex check - blank value passed check

---

app/code/community/Nexcessnet/Turpentine/Helper/Cron.php
app/code/community/Nexcessnet/Turpentine/Model/Observer/Cron.php
app/code/community/Nexcessnet/Turpentine/etc/config.xml
app/code/community/Nexcessnet/Turpentine/etc/system.xml

On smaller servers the volume of crawler requests can use up resources. This commit adds the ability to throttle the crawler by sleeping after a given number of requests, giving the server a chance to cool down.

add ability to throttle crawler requests

---

app/code/community/Nexcessnet/Turpentine/Block/Poll/ActivePoll.php

Now checks to make sure the Mage_Poll module is active and doesn't have it's output disabled to fix https://github.com/nexcess/magento-turpentine/issues/1093 (poll block showing up even if the module output is disabled in the backend).

Fix for issue #1093 - poll still displaying when module output disabled

---

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php

To improve the cache rate, when User-Agent normalization is enabled - rather than using separate User-Agents for each browser, this simply tries to detect "mobile" and anything else is categorized as "other".

Condensed the UA "buckets" down to just "mobile" and "other" 

---

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php
app/code/community/Nexcessnet/Turpentine/etc/system.xml

This adds the an option Enable Varnish Command Logging which if enabled will cause all commands sent to Varnish to be logged to the system.log - or the custom turpentine log file (if enabled).
This can cause logs to grow quickly, especially if the VCL is applied to varnish often!
Should solve https://github.com/nexcess/magento-turpentine/issues/1206 - and replaces  PR https://github.com/nexcess/magento-turpentine/pull/1215

Adds and implements an option to log all commands sent to Varnish

---

app/code/community/Nexcessnet/Turpentine/controllers/EsiController.php

Issue #1213
Create a virtual <reference>-node, append the global formkey-block-node (if found) and call $layout->generateBlocks on it. That way $layout->getBlockHtml() can be called within ESI-Blocks.

#1213: Generate global blocks like formkey for ESI-Blocks

---

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php
app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Version3.php
app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Version4.php
app/code/community/Nexcessnet/Turpentine/etc/config.xml
app/code/community/Nexcessnet/Turpentine/etc/system.xml

Creates a new configuration field where you can specify the location of a custom VCL **template** - which will be used when you generate a new VCL instead of the default templates that ship with Turpentine.
*Important* - you still need to specify your version of Varnish (or let it detect automatically).
Should solve https://github.com/nexcess/magento-turpentine/issues/1209

Allows Custom VCL template

---

util/warm-cache.sh

The script has been changed to be more flexible
- Can set the User-Agent to whatever you like (-a)
- Can dynamically pull URLs from a sitemap, or use a static URL file (-u)
- Can set the number of concurrent "users" to use when warming the cache - the list of URLs will be split between the available "users"

Adds more flexibility/options to warm-cache.sh

---

app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl

This adds substantially more information the varnishlog in Varnish 4. Before, there was no logging of calls to `hash_data` (at least in Varnish 4.0.3) which made it more difficult to debug issues with cache misses. This adds the item being added to the hash as well as its value.

Adds better logging of hash_data calls in vcl_hash

---

app/code/community/Nexcessnet/Turpentine/etc/config.xml

A small change with big impact on performance tests using newer versions of Siege.
The previous Crawler UserAgent regular expression does not match newer versions of Siege. This resulted in all Siege requests being passed to the PHP backend server, because Siege has no session.
I tested all listed UserAgents, these do all match the new regexp:
JoeDog/1.00 [en] (X11; I; Siege 2.59)
Mozilla/5.0 (pc-x86_64-linux-gnu) Siege/3.0.8
Mozilla/5.0 (unknown-x86_64-linux-gnu) Siege/4.0.0-beta5
ApacheBench/2.3
Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
magespeedtest.com
Nexcessnet_Turpentine/0.6.8 Magento/1.9.0.1 Varien_Http_Client
Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; PTST 2.295)
Fix for existing installs using N98-Magerun:
n98-magerun.phar …

Fixed Crawler UserAgent regexp to match newer Siege versions.

---

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php

Bugfix in "Normalize Encoding": When a visitor accepts `*` this means it also accepts `gzip`.
This is a performance fix for newer versions of Siege. They use `Accept-Encoding: *`
Often caches are warmed for `Accept-Encoding: gzip` because all modern browsers do accept Gzip.

Bugfix in "Normalize Encoding" for visitors who accept "*"

---

.gitignore
app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php
app/code/community/Nexcessnet/Turpentine/etc/config.xml
app/code/community/Nexcessnet/Turpentine/etc/system.xml
app/code/community/Nexcessnet/Turpentine/misc/version-2.vcl
app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl
app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl

When multiple subroutines with the same name exist in Varnish, they get concatenated.
The existing 'custom_include.vcl' file is appended to the VCL. It can't be used to expand the 'sub vcl_recv' because the existing one contains 'return (pipe)' statements. Whatever you add will not be executed in a lot of situations.
I added a 'custom_include_top.vcl' file, which is prepended to the VCL. This allows you to override everything. For example you can include a 'return (pipe)' yourself to skip the default Turpentine VCL :-)

Feature: Custom file include on top of VLC

---

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php

Hi, small change to regular expression because extension can't determine correct buffer size on CentoOS 7 and varnish-4.0.3 revision b8c4a34
Some how it shows value in incorrect format, in bytes instead of kilobytes or what ever.
```
varnishadm param.show | grep cli_buffer
cli_buffer                 240000b [bytes]
```

Added one more format for configuration regexp

---

app/design/frontend/base/default/layout/turpentine_esi.xml

The default Magento "Remember Me" functionality provides a "Not <name>?" link in the header to allow a customer to clear the persistent cookie on return to Magento (after default session expiration).
Clicking this link with Turpentine enabled doesn't currently cause the header to be purged.
This fix adds the "persistent_session_expired" event to the default header's flush_events. This event is dispatched by Mage_Persistent_IndexController::_cleanup() after the user clicks on the "Not <name>?" link.

Fix issue with customer name not being removed from header when clearing persistent cookie

---

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php
app/code/community/Nexcessnet/Turpentine/etc/system.xml
app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl
app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl

I am using Varnish as front door listen on public IP & port 80, and using NGINX listen on port 80 for the backend, and 443 for HTTPS.
The issue is when I enter the HTTP URL with parameters it always redirects to home page. For example,  I enter http://example.com/about-us , it redirects to https://example.com 
The fix will keep the URL parameters when redirecting from HTTP to HTTPS. So when I enter http://example.com/about-us, it will redirect to https://example.com/about-us
Thanks to considering to check and merge.

Fix the issue when redirect HTTP to HTTPS

---

app/code/community/Nexcessnet/Turpentine/Helper/Esi.php
app/code/community/Nexcessnet/Turpentine/Model/Observer/Esi.php
app/code/community/Nexcessnet/Turpentine/controllers/EsiController.php

Some themes like Ultimo use `unsetChild` to remove default Magento blocks, and create the block again with the same name but other properties in another place.
The `unsetChild` action does not remove a block from the XML, only from the object structure.
When an ESI block is requested, the controller was only looking for the name of the block in the layout XML, so in some cases it picked the removed block.
I added a check for the `setEsiOptions` action inside the block XML, with a fallback to the old behaviour.

Fix for picking the wrong block from the layout when multiple blocks found - v2

---

app/code/community/Nexcessnet/Turpentine/Model/Observer/Varnish.php

Example of the notice fixed here:
`2016-12-15T11:01:56+00:00 ERR (3): Notice: Constant CM_REDISSESSION_LOCKING_ENABLED already defined  in /path/to/httpdocs/app/code/community/Nexcessnet/Turpentine/Model/Observer/Varnish.`
This problem appears when other extensions are also setting `CM_REDISSESSION_LOCKING_ENABLED`.

Small fix for notice when CM_REDISSESSION_LOCKING_ENABLED is already defined

---

app/code/community/Nexcessnet/Turpentine/Model/Observer/Esi.php

I had problem with custom **$_GET** params, the ESI Observer set ESI url and remove all my custom params.
This PR will get params form origin URL and add `_query` to  `$urlOptions` so the ESI url will contains all params from the origin url
```
$urlOptions['_query'] = Mage::app()->getRequest()->getParams();
```

Keep params from original url

---

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php

Is there a reason that the maintenance page has a 404 response and not a 503? All good if there is, I just thought using a 503 made more sense.

use 503 response for maintenance page rather than 404

---

app/code/community/Nexcessnet/Turpentine/Helper/Esi.php

If I have a block declared 2 times (ie: "catalog.product.related", re-declared in the EE targetrule.xml) I should get the last one, as Magento would do.

When rendering an ESI, get last block found in the XML instead of the first

---

app/design/frontend/base/default/layout/turpentine_esi.xml

This ensures that no user data is stored in Varnish (the contact form is pre-filled with user data for logged in users).

added ESI options for contact form, #116, #486

---

app/code/community/Nexcessnet/Turpentine/Helper/Cron.php

MageWorx_XSitemap used to use `xsitemap` for their models, but they now use `mageworx_xsitemap`.

fixed MageWorx_XSitemap compatibility

---

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Version2.php
app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Version3.php
app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Version4.php

I want to add site specific customisations to my vcl that would be based on Magento config but don't make sense to be added to turpentine for everyone.
Adding this event allows me to create a custom extension which will add additional template vars which I can then use in my vcl.

Dispatch event in _getTemplateVars to allow other extensions to add custom vcl template variables

---

app/code/community/Nexcessnet/Turpentine/Helper/Esi.php

https://github.com/nexcess/magento-turpentine/issues/1403

Fix ESI default ttl based on session.gc_maxlifetime

---

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php

The http to https redirect wasn't working for me. I figured out it was because my frontend website base urls were different to what we have at global scope. The existing code gets the base url from config and checks that the request host matches the configured base urls before doing the redirect. In my case this never matched as it was the admin base url not the frontend store view. 
This pull requests fetches all secure and unsecure base urls from all store views and adds them all to the existing regex

check for hosts from every store view in http -> https redirect

---

app/code/community/Nexcessnet/Turpentine/Model/Observer/Varnish.php
app/code/community/Nexcessnet/Turpentine/controllers/Varnish/ManagementController.php

In some places the value of strip_vcl_whitespace was not being checked,
e.g. The VCL saved to disk on config change was always being stripped.

Apply the option `strip_vcl_whitespace` everywhere

---

app/code/community/Nexcessnet/Turpentine/Helper/Esi.php

We like to keep notices to keep our code clean. These lines gave a notice in PHP 7.x:
```
2018-09-13T08:27:47+00:00 ERR (3): Notice: Only variables should be passed by reference  in /path/to/httpdocs/.modman/magento-turpentine/app/code/community/Nexcessnet/Turpentine/Helper/Esi.php on line 384
2018-09-13T08:27:47+00:00 ERR (3): Notice: Only variables should be passed by reference  in /path/to/httpdocs/.modman/magento-turpentine/app/code/community/Nexcessnet/Turpentine/Helper/Esi.php on line 389
```

Fix for notice 'Only variables should be passed by reference' in PHP 7.

---

app/code/community/Nexcessnet/Turpentine/Block/Core/Messages.php

Following up on #940 here. The distinction between `getHtml` for the `global_messages` and `getGroupedHtml` for the `messages` is quite old:
https://github.com/nexcess/magento-turpentine/blame/44d7b7627b2656ae87aa29b5a6a52e4e774fd33d/app/code/community/Nexcessnet/Turpentine/Block/Core/Messages.php#L319-L327
It should be absolutely okay to always use `getGroupedHtml`:
- for the `messages`, `getGroupedHtml` is already used, so nothing changes for this block
- the `global_messages` block is always called via `<?php echo $this->getChildHtml('global_messages') ?>`
- `Mage_Core_Block_Abstract::getChildHtml` calls `Mage_Core_Block_Abstract::_getChildHtml`
- `Mage_Core_Block_Abstract::_getChildHtml` calls `Mage_Core_Block_Abstract::toHtml`
- `Mage_Core_Block_Abstract::toHtml` calls …

fixed admin_messages in frontend, fixes #940
