nexcess/magento-turpentine

app/code/community/Nexcessnet/Turpentine/Helper/Debug.php, app/code/community/Nexcessnet/Turpentine/etc/config.xml, app/code/community/Nexcessnet/Turpentine/etc/system.xml
Make a custom log file configurable as described in issue #510
=> Custom log file

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php, app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl
this one fixes duplicated frontend cookie bug (or unconfirmed-bug?). I am sure some people could implement this even better. But i just wanted to give an idea of how to understand, reproduce and fix this bug. My company tried to fix this problem since 2013 never founding the reason nor being able to reproduce, so i am sure this fix will have an importance for many turpentine users.
=> refs #84, #345, #435, #477, #690, #774 Fixed duplicated frontend cookie bug

app/code/community/Nexcessnet/Turpentine/Model/Observer/Esi.php, app/code/community/Nexcessnet/Turpentine/etc/config.xml, app/code/community/Nexcessnet/Turpentine/misc/version-2.vcl, app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl
=> Added customer_group access option to cache based on customer group

app/code/community/Nexcessnet/Turpentine/Helper/Esi.php
Initialize variable with Magento way of doing things so we can extend it later
=> Replace  Nexcessnet_Turpentine_Model_Dummy_Request with Magento model

app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl
Also replaced all tabs by spaces.
=> Fixed bug in commit 9b0c601: one closing brace too much.

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php
The code here is doing a boolean check but the setting is saved as a string (no, yes or yes_admin)
As per #904 this fixes the config geneator
=> Fix for: ignores backend settings #904

contrib/tools/esi-decoder.php
Added button to the ESI Decoder tool to show the content of the ESI block.
Added auto-detect for Magento root.
=> ESI Decoder: Button to show block content.

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php
getStoreConfigFlag returns a boolean, it should be getStoreConfig
=> fix use of getStoreConfig in getDefaultBackend and getAdminBackend

app/code/community/Nexcessnet/Turpentine/Helper/Data.php, app/code/community/Nexcessnet/Turpentine/Helper/Debug.php, app/code/community/Nexcessnet/Turpentine/Model/Config/Select/Version.php, app/code/community/Nexcessnet/Turpentine/Model/Observer/Esi.php, app/code/community/Nexcessnet/Turpentine/Model/Shim/Mage/Core/Config.php, app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin.php, app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php, app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Version2.php, app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Version4.php, app/code/community/Nexcessnet/Turpentine/controllers/Adminhtml/CacheController.php, app/code/community/Nexcessnet/Turpentine/controllers/Varnish/ManagementController.php, contrib/tools/esi-decoder.php
@miguelbalparda requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/nexcess/magento-turpentine/
=> Scrutinizer Auto-Fixes

app/code/community/Nexcessnet/Turpentine/Model/Observer/Ban.php
Invalidating cms pages with url enging with slash. Like: http://domain.com/about-us/
=> Invalidating cms pages with url enging with slash

app/design/frontend/base/default/layout/turpentine_esi.xml
Adds an ESI caching policy for the cookie notice block.
=> Added ESI policy for cookie notice block

app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl
A pull request based on conversation started in https://github.com/nexcess/magento-turpentine/issues/1129.
=> use pass instead of pipe on non GET requests to improve performance

build/build_package.py, build/mage-package.xml
=> Support PHP7

app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl
See https://github.com/nexcess/magento-turpentine/pull/1078
and https://github.com/nexcess/magento-turpentine/issues/1180
=> Update version-3.vcl normalisation

app/code/community/Nexcessnet/Turpentine/Model/Observer/Esi.php
This improves the block logging by adding information about each block as Turpentine decides whether to inject an ESI tag for the block.
=> Enhanced block logging

app/code/community/Nexcessnet/Turpentine/Helper/Data.php
https://github.com/nexcess/magento-turpentine/issues/963 For more info about the issue
=> #963 Fix the Nginx 403 issue with urls which are starting with a dot

app/design/frontend/base/default/template/turpentine/ajax.phtml
=> #1270 Fix: Improve condition to support safari browser Event

app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl
Add the customer group caching to the varnish 4 template
=> #838 Add customer_group caching to varnish 4 template

app/code/community/Nexcessnet/Turpentine/Block/Management.php
=> Removed unused code

app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php, app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl, app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl
This PR is the fix for issue #1312
=> Fix issue #1312

app/code/community/Nexcessnet/Turpentine/Model/Config/Select/Version.php, app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin.php, app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php, app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php
I've tested it with varnish 4.1.3 and magento 1.9.2.4-patch3 firegento/magento
=> varnish 4.1 compatibility

app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl
Reverts nexcess/magento-turpentine#1132
=> Revert "use pass instead of pipe on non GET requests to improve performance"

app/code/community/Nexcessnet/Turpentine/misc/version-2.vcl, app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl, app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl
Issue #1409
Keeping `Cache-Control` header by default, overriding when needed.
=> Fix issue #1409: Solved by keeping Cache-Control header

util/warm-cache.sh
=> Fixed comments

app/code/community/Nexcessnet/Turpentine/Block/Adminhtml/Cache/Grid.php
- Included options validation to avoid hide the options if full page cache and varnish cache were enabled at the same time.
=> - Update Grid.php

app/code/community/Nexcessnet/Turpentine/etc/config.xml
See https://www.bing.com/webmaster/help/which-crawlers-does-bing-use-8c184ec0
=> added Bing and Baidu bots to crawler user agents

app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl
=> Fix Typo in VCL

app/code/community/Nexcessnet/Turpentine/etc/config.xml
See https://support.google.com/webmasters/answer/1061943
=> added more Google bot user agents
